name: CI

on: [push, pull_request]

jobs:
  build_gh1dx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/arkhelper
          chmod +x dependencies/dtab
          chmod +x dependencies/superfreq
          dependencies/arkhelper dir2ark ./_ark ./gen -n MAIN -s 4073741823
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: GH1DX-PS2
          path: |
            gen
            iop
            SLUS_212.24
            SYSTEM.CNF
